### PR TITLE
Add LibRavatar support (#114)

### PR DESCRIPTION
**Pull request by 0xMRTT**
A more privacy concerned and decentralised solution is the libravatar protocol. In short it's a selfhosting gravatar.

### CODE REVIEW

**Comment by johanneswilm** [comment]
@0xMRTT Looks good. Would you mind updating the code to make the tests parse? I assume that means dropping Python 3.6 support and replacing it with 3.11.

**Comment by 0xMRTT** [comment]
@johanneswilm I've fixed the CI

- I've updated coverage to 7.1.0 because I dropped 3.6 
- I've added 3.6
- I've refactored the matrix in GH-action
- I've added a `pyproject.toml` file because it's now a standard
- I've added a `requirements.txt` file
- I've added `dnspython` as a dependency for LibRAvatar

Now, it's good !

**Comment by johanneswilm** [comment]
@0xMRTT Thank you so much!

**Comment by johanneswilm** [comment]
@0xMRTT I guess we need to make a release then. This is interoducing new functionality, but as far as I can tell, it's not breaking anything existing, so that would be an argument for a minor version release. On the other hand, we removed the tests for Python .6, so I guess that could mean that we either have or will be introducing code that will require Python 3.7+. I'm not sure if that means we should make a major version release. What would you say? Is it likely that the things you introduced broke anything for existing installations?

**Comment by 0xMRTT** [comment]
Hi @johanneswilm 

I agree to make a new release. I didn't introduced any 3.7 specific code. I just dropped support for 3.6 because 3.6 is EOL and `coverage` doesn't support 3.6  anymore (coverage 6.2 caused an issue with python 3.11). This release can be either a major or a minor one.

**Pull request merged**
